namespace TechArtPortfolio.Layout.Models;

public static class CodeData
{
    public static readonly string TestCode = "GalaxyContext::GalaxyContext(Function<PlayerInput> getPlayerInput)\n    {\n        this->getPlayerInput = getPlayerInput;\n\n        opaquePass = Rendering::IRenderPass::FetchFromRegister<Rendering::DrawOpaquePass>(\n            std::string(Rendering::OPAQUE_PASS));\n\n        skyboxPass = Rendering::IRenderPass::FetchFromRegister<Rendering::DrawSkyboxPass>(\n            std::string(Rendering::SKYBOX_PASS));\n\n        deferredShadePass = Rendering::IRenderPass::FetchFromRegister<Rendering::DeferredShadePass>(\n            std::string(Rendering::DEFERRED_SHADE_PASS));\n\n        drawUIPass = Rendering::IRenderPass::FetchFromRegister<Rendering::DrawUIPass>(\n            std::string(Rendering::UI_PASS));\n\n        defaultLitMaterial = std::make_shared<Rendering::Material>(\"DefaultLit\");\n        defaultLitMaterial->SetColor(\"_BaseColor\", glm::vec4(0, 0, 0, 1));\n\n        // catTexture = std::make_shared<Rendering::Texture2D>(\"Tex_CatAnguish\");\n\n        catLitMaterial = std::make_shared<Rendering::Material>(\"SphereRaymarch\");\n        // catLitMaterial->SetTexture(\"_AlbedoMap\", catTexture.get());\n\n        catLitMaterial->SetColor(\"_BaseColor\", glm::vec4(0.5f, 0.6f, 0.2f, 1));\n        catLitMaterial->SetVector(\"_Random\", glm::vec4(0.8f));\n        catLitMaterial->SetInt(\"_ShapeIndex\", 1);\n        catLitMaterial->SetFloat(\"_Smoothness\", 0.5f);\n        catLitMaterial->SetFloat(\"_Metalllic\", 0.8f);\n\n        computePerlinPass = Rendering::IRenderPass::FetchFromRegister<Rendering::ComputePerlinPass>(\n            \"Compute Perlin\", 90, defaultLitMaterial.get());\n\n        tornadoPass = Rendering::IRenderPass::FetchFromRegister<Rendering::ComputeTornadoParticlesPass>(\n            \"Compute Tornado\", 80);\n\n        tornadoRenderPass = Rendering::IRenderPass::FetchFromRegister<Rendering::RenderTornadoPass>(\n            \"Render Tornado\", 400);\n\n        mirandaSansFont = Rendering::FontAsset::Get(\"MirandaSans\");\n        fontMaterial = std::make_shared<Rendering::FontMaterial>(mirandaSansFont);\n\n        fontMaterial->SetColor(glm::vec4(1, 0, 1, 1));\n        fontMaterial->SetSize(0.1f);\n    }";
    
    // vulkan
    public static readonly string VulkanRenderPass = 
        "namespace Beer::Rendering\n{\n    void DrawOpaquePass::OnRenderSetup(const RenderContext& context)\n    {\n        context.BlackBox->ReallocateIfNeeded(GBUFFER_ALBEDO,\n            Core::Screen::Width(),\n            Core::Screen::Height(),\n            Core::Screen::ColorFormat());\n\n        context.BlackBox->ReallocateIfNeeded(GBUFFER_NORMAL,\n            Core::Screen::Width(),\n            Core::Screen::Height(),\n            GBUFFER_NORMAL_FORMAT);\n\n        context.BlackBox->ReallocateIfNeeded(GBUFFER_MAT,\n            Core::Screen::Width(),\n            Core::Screen::Height(),\n            Core::Screen::ColorFormat());\n    }\n\n    void DrawOpaquePass::Execute(CommandBuffer* commandBuffer, const RenderContext& context)\n    {\n        System::DrawRequest drawRequest = System::DrawRequest(commandBuffer,\n            context,\n            Rendering::ShaderPassType::Opaque,\n            System::ContextMask(System::CTXT_GALAXY_BITS),\n            System::LayerMask(System::LAYER_ALL_BITS));\n\n        Core::DrawCallPool drawPool = context.Register->GetDrawCallPool(drawRequest);\n        drawPool.BindDrawCalls();\n    }\n\n    PassDependencyList DrawOpaquePass::GetDependencies() const\n    {\n        PassDependencyList dependencies = PassDependencyList(name);\n        dependencies.AddDependencies(RenderGlobalUtilities::GetGBufferDependencies(true));\n\n        dependencies.AddDependency(PassDependency(MAIN_DEPTH,\n            ResourceAction::DepthWrite,\n            ResetOperator::ClearDepth()));\n\n        return dependencies;\n    }\n} // namespace Beer::Rendering";

    public static readonly string VulkanShader =
        "#include \"Core/BeerMacros.slang\"\n\nimport Core.BeerCore;\nimport Core.Beer3D;\nimport BeerLit;\n\n// Micah: here are the material properties\nBIND_MATERIAL_DATA\ncbuffer MaterialData\n{\n    float4 _BaseColor;\n    float _Smoothness;\n    float _Metallic;\n};\n\n// Micah: we can bind material textures / ssbo's\nBIND_MATERIAL_TEX(1) Sampler2D _AlbedoMap;\n\nstruct MeshData\n{\n    M_POSITION;\n    M_NORMAL;\n    M_UV;\n};\n\nstruct VertexData\n{\n    float4 positionCS : SV_Position;\n    float3 positionWS;\n    float3 normalWS;\n    float2 texCoord;\n}\n\n// Micah: these are the pass settings, exported to JSON\n//$ Pass Opaque\n//$ Vertex DefaultLitVert\n//$ Fragment DefaultLitFrag\n//$ Cull Back\n//$ Blend Off\n//$ Zwrite On\n\nVERT VertexData DefaultLitVert(MeshData input, INSTANCEID)\n{\n    // Micah: helper Macro to get transform data\n    GETMODELDATA\n    VertexData output;\n    float4 positionWS = mul(transform.objToWorldMat, float4(input.positionOS, 1));\n    output.positionCS = mul(_ViewProjMat, positionWS);\n    output.positionWS = input.positionOS.xyz;\n    output.normalWS = mul(transform.objToWorldDirMat, float4(input.normalOS, 1)).xyz;\n    output.texCoord = input.texCoord;\n    return output;\n}\n\nFRAG float4 DefaultLitFrag(VertexData input) : SV_Target\n{\n    float4 sample = _AlbedoMap.Sample(input.texCoord);\n\n    Lit.BRDF brdf = Lit.BRDF(GetMainLight(input.positionWS), \n        GetViewDirectionWS(input.positionWS),\n        input.normalWS,\n        sample.rgb,\n        _Smoothness,\n        _Metallic);\n\n    return float4(brdf.Shade(), 1);\n}";
    
    // painterly
    public static readonly string FloodAlgorithm =
        "FloodOutput FloodPropagate(FloodInput input)\n{\n    FloodOutput output;\n    output.distance = input.distance;\n    output.uv = input.floodUv;\n\n    [loop]\n    for (int x = -1; x <= 1; x++)\n    {\n        [loop]\n        for (int y = -1; y <= 1; y++)\n        {\n            if (x == 0 && y == 0)\n                continue;\n\n            float2 currentUv = input.sampleUv + float2(x, y) * input.texelSize;\n            currentUv = clamp(currentUv, 0, 0.999f);\n\n            float2 floodUv; float floodDist;\n            SampleFlood(currentUv, floodUv, floodDist);\n\n            float3 currentId; float unused;\n            SampleHash(floodUv, currentId, unused);\n\n            if (!IsSameCell(currentId, input.cellId))\n                continue;\n\n            [flatten]\n            if (floodDist < output.distance)\n            {\n                output.distance = floodDist;\n                output.uv = floodUv;\n            }\n        }\n    }\n\n    return output;\n}";

}